### ISSUE TITLE
Any room that isn't `matrix-crdt-test` doesn't seem to connect

### ISSUE THREAD

**Issue by juliankrispel** [YousefED/Matrix-CRDT#13]
When connecting to a room that isn't `matrix-crdt-test` initialization never completes and requests keep being sent to messages api.

Steps to reproduce:

1. Connect to room that isn't prefixed with `matrix-crdt-test`
2. Open Network Tab
3. See endless requests to messages api 

Loom walkthrough -> https://www.loom.com/share/ce12cdbecf494c4d987449e77dc7b62f

**Comment by juliankrispel** [comment]
> Hi @juliankrispel !
> 
> The examples are configured to only connect to rooms with a prefix of `matrix-crdt-*` (
> 
> https://github.com/YousefED/Matrix-CRDT/blob/37b5e60839a1431749a51a491e79b46fcab71b98/examples/rich-text-tiptap/src/login/LoginForm.tsx#L33
> 
> )
> I configured it like this to avoid experimental users from unintentionally spamming "production" matrix rooms.
> 
> Of course, when using the library in your code (instead of the example), there is no such limitation

Hello @YousefED - the endless requests are still happening for me :/ - for any other room than `matrix-crdt-test` - it `MatrixReader.ts` seems to fire these requests. Will do some more debugging when I have time

**Comment by YousefED** [comment]
What's the room name that you're currently using? Does your user have access to it?
