### ISSUE TITLE
Buffer is not defined error

### ISSUE THREAD

**Issue by ysds** [YousefED/Matrix-CRDT#18]
"When I run the "todo-simple-react" example and try to add a todo, I get the following error.

This may be related to this.
https://github.com/webpack/changelog-v5/issues/10

<img width="1531" alt="image" src="https://user-images.githubusercontent.com/4065765/197456150-ee5f98b3-c5d3-4007-8d8e-eee91a4b0bc0.png">

**Comment by YousefED** [comment]
Thanks @ysds,

Do you get the same error on https://klwxt.csb.app/, or only when you build it yourself?

The current version of Matrix-CRDT doesn't use webpack anymore (we have migrated to Vite)

**Comment by ysds** [comment]
Sorry for the late reply.
I was unable to open the demo for a while due to the "TypeError Could not fetch dependencies, please try again in a couple of seconds" issue in codesandbox.

Now I can access that demo without any problem and I can't confirm the Buffer issue.

Also, I raised my local Node version from v16 to v18 and this problem did not occur.

**Comment by mgood** [comment]
I'm seeing the same issue when trying to set this up with a SvelteKit/Vite project.
```
"matrix-crdt": "^0.2.0",
"matrix-js-sdk": "^22.0.0",
```
I added this Buffer polyfill to get around the problem for now:
https://github.com/feross/buffer

I see there's another location in the code using `lib0/buffer.fromBase64` which seems like it might be a suitable replacement for the base64 encoding/decoding that would work in the browser without a polyfill.

**Comment by YousefED** [comment]
Added a Vite example now that shows how you can set it up, see this note in the main Readme:

Note for Vite / non-webpack If you're using Vite, or other non-webpack builds, note that matrix-js-sdk depends on certain polyfills available. See the [Vite example](https://github.com/YousefED/Matrix-CRDT/blob/main/examples/todo-simple-react-vite) and https://github.com/matrix-org/matrix-js-sdk/issues/2903.
