### ISSUE TITLE
About E2EE support

### ISSUE THREAD

**Issue by kelvinkoko** [YousefED/Matrix-CRDT#26]
Thanks for the nice provider. I come to know this yjs provider from this https://discuss.yjs.dev/t/matrix-crdt-yjs-provider-that-connects-to-matrix/958
and it mentioned E2EE is in the plan. Would like to know does the latest version here already support E2EE?

**Comment by jacobcoro** [comment]
It does not. Check out the [WIP](https://github.com/YousefED/Matrix-CRDT/pull/17) Pull Request. For this feature. If you feel like diving in to the source maybe you can help with some of the issues Yousef encountered.

**Comment by kelvinkoko** [comment]
Thanks for the info! i will check that PR, let me close this first
